### ISSUE TITLE
Problem libmicon with TeraStation TS5600D

### ISSUE THREAD

**Issue by vemax78** [1000001101000/Python_buffalo_libmicon#1]
Hi,
I have a TeraStation TS5600D (5000 Series). I try examples of libmicon python library but I found some problems.

Work:
* Indication/ETH LED
* Brightness display LCD
* Color display LCD
* HDD LED
* Buzz

Don't work
* Text display LCD (All example is always empty)
* Catch press button

**Comment by 1000001101000** [comment]
is there anything else you want me to look at for this issue?

**Comment by vemax78** [comment]
No thanks
Massimo

Il Sab 16 Gen 2021, 00:56 1000001101000 <notifications@github.com> ha
scritto:
